<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_UpdateEventTimeStampWithSystemTime" Id="{6e15ab70-44aa-44fe-86f0-070b91b3947a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_UpdateEventTimeStampWithSystemTime 
VAR_INPUT
	stEvent : REFERENCE TO St_Event ;
END_VAR
VAR
	fbGETSYSTEMTIME : GETSYSTEMTIME ;
	
	stFileTime : T_FILETIME ;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbGETSYSTEMTIME (timeLoDW => stFileTime.dwLowDateTime,
				 timeHiDW => stFileTime.dwHighDateTime) ;
				 
stEvent.dtTimeStamp := FILETIME_TO_DT(fileTime := stFileTime ) ;

]]></ST>
    </Implementation>
    <LineIds Name="F_UpdateEventTimeStampWithSystemTime">
      <LineId Id="7" Count="0" />
      <LineId Id="20" Count="2" />
      <LineId Id="25" Count="0" />
      <LineId Id="24" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>